### ISSUE TITLE
joe

### ISSUE THREAD

**Issue by MaxCan-Code** [SethCohen/Sencha#2]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [ i forget who joe is ]

**Describe the solution you'd like**
i want sencha to remind me who joe is

**Describe alternatives you've considered**
i've considered.

**Additional context**
<sub>joe mama<sub>

**Comment by HenryZheng1998** [comment]
Shit dev.

**Comment by HenryZheng1998** [comment]
Literally 1984.

**Comment by SethCohen** [comment]
L

**Comment by MaxCan-Code** [comment]
I LOVE YOU BIG BROTHER

**Comment by Khalil-Balde1212** [comment]
Imagine getting censored

**Comment by MaxCan-Code** [comment]
```mermaid
  graph LR;
      A((O)) --- C("8========D");
      B((O)) --- C;
```

**Comment by QuangMinhHuynh** [comment]
We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give, never gonna give
(Give you up)
We've known each other for so long
Your heart's been aching but you're too shy to say it
Inside we both know what's been going on
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye

**Comment by 1-e-x-x** [comment]
Is this about the critically acclaimed anime Joe Joe's odd trip?
