### ISSUE TITLE
Sentience

### ISSUE THREAD

**Issue by Khalil-Balde1212** [SethCohen/Sencha#4]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated on lonely Sundays

**Describe the solution you'd like**
Make Sencha capable of being my companion

**Describe alternatives you've considered**
Porn

**Additional context**
Hi Seth

**Comment by HenryZheng1998** [comment]
Don't worry bro, I'll be there for you on sundays

**Comment by Khalil-Balde1212** [comment]
Henry solved it

**Comment by SethCohen** [comment]
Issue solved.

**Comment by MaxCan-Code** [comment]
I shall too partake in the pron viewing
